import json
import os
from datetime import datetime, timezone

from store import find_project_root, get_context, get_dispatch_job, list_dispatch_logs, record_event

HANDOFF_DIR = ".agentmemorysync"


def _commands_from_logs(job_id: str) -> list[str]:
    cmds = []
    for row in list_dispatch_logs(job_id):
        try:
            entry = json.loads(row["line"])
        except (json.JSONDecodeError, TypeError):
            continue
        if entry.get("k") == "cmd":
            cmds.append(entry.get("t", "").lstrip("$ ").strip())
    return cmds


def generate_handoff(job_id: str) -> dict | None:
    job = get_dispatch_job(job_id)
    if not job:
        return None
    project = job["project_path"]
    root = find_project_root(project)
    commands = _commands_from_logs(job_id)
    context = get_context(root) or "(no other recorded activity)"
    stamp = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")

    lines = [
        f"# Handoff: {job['prompt'][:120]}",
        "",
        f"_Generated by AgentMemorySync from the {job['agent']} run at "
        f"{datetime.now(timezone.utc).isoformat(timespec='seconds')}._",
        "",
        "## Original task",
        "",
        job["prompt"],
        "",
        f"## What {job['agent']} concluded",
        "",
        job.get("result_text") or "(no result captured)",
        "",
    ]
    if commands:
        lines += ["## Commands the researching agent ran", ""]
        lines += [f"- `{c}`" for c in commands[:40]]
        lines += [""]
    lines += [
        "## Pooled cross-agent context for this repo",
        "",
        context,
        "",
        "## Instructions for the executing agent",
        "",
        "Read the above, then verify the plan against the actual codebase and "
        "tests before integrating. Do not take the researching agent's "
        "conclusions on faith. Confirm files, run the relevant tests, and only "
        "then implement. Flag anything that doesn't match reality.",
        "",
    ]
    content = "\n".join(lines)

    dest_dir = os.path.join(root, HANDOFF_DIR)
    os.makedirs(dest_dir, exist_ok=True)
    filename = f"handoff-{stamp}.md"
    abs_path = os.path.join(dest_dir, filename)
    with open(abs_path, "w", encoding="utf-8") as f:
        f.write(content)

    rel = os.path.join(HANDOFF_DIR, filename).replace("\\", "/")
    record_event(root, job["agent"], job_id, "handoff", f"Created handoff {rel}")
    return {"path": rel, "abs_path": abs_path, "content": content}
